server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: file:./config-repo  #https://your-git-repo-url  # ???? Git ???

          #default-label: master  # ??

  application:
    name: config-server
